### ISSUE TITLE
General Improvements for Sacha J.

### ISSUE THREAD

**Issue by samtaggart** [ourworld-tsc/www_zanzibarhotel#1]
**General Notes from Kristof**

- Needs to show why we are unique, what we have, what will come
- Not too much about doing good, come across in a positive way, but nothing rebellious
- Say that we are looking for co-financers, but we don't include too many details on website (tell them to reach out for more details)
- Needs to talk about digital nomads and business people
- Needs to talk about full blown apartment and office and JP (all as one thing)
- Also need the boats in there ... we should probably add the video from Kristof
- Need to add a roadmap

**General Tasks**

- [x] Add favicon (see comments for attachments)

**Home Page Tasks**

- [x] Add two new locations in Karibu Zanzibar block – Seaview Apartments and OurOffice – new order should be ... top-left Jungle Paradise, top-right Seaview Apartments, bottom-left OurOffice, bottom-right Chumbe Island

**About Page Tasks**

- [x] About Page needs attention ... look at formatting and photos

**Action Page Tasks**

- [x] New image for header

**Comment by samtaggart** [comment]
[Untitled design (7).zip](https://github.com/ourworld-tsc/www_zanzibarhotel/files/10742398/Untitled.design.7.zip)

Here are three options for the favicon. Please test all three and let me know which one works best.

**Comment by Sacha156** [comment]
alright, will do

**Comment by samtaggart** [comment]
Ended up going with the OurWorld logo for the favicon
